<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content=""/>
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <title>Zend Framework ESI</title>
</head>
<body>
    <table border="1" width="800" cellpadding="1" cellspacing="2" align="center">
        <tr>
            <td colspan="2"><?php echo $this->esi('index','header') ?></td>
        </tr>
        <tr>
            <td width="100"><?php echo $this->esi('index','menu') ?></td>
            <td height="400"><?php echo $this->layout()->content ?></td>
        </tr>
        <tr>
            <td colspan="2"><?php echo $this->esi('index','footer') ?></td>
        </tr>
    </table>
</body>
</html>